### PR TITLE
Strict grid snap (addresses #74)

### PR DESCRIPTION
**Pull request by bgschiller**
Video demonstrating the new toggle: https://trello-attachments.s3.amazonaws.com/58d428743111af1d0a20cf28/599b3f6992c6964e7c2145db/9048fe1fbe6c3e904d87172807e1b6b3/recording.webm

### CODE REVIEW

**Comment by ljbrackney** [comment]
That looks great!

**Review by gh-23378 — APPROVED** [review]
is snapping-thoughts something we want in the repo, or just notes/something to add as a comment on one of the issues?

**Comment by bgschiller** [comment]
@devKate I just didn't want to lose it. We can delete it sometime down the line when this is more settled.

**Comment by gh-23378** [comment]
fair enough! :)

**Pull request merged**
