### PR TITLE
fix backwards edge case

### PR DESCRIPTION
**Pull request by bgschiller**
as described in scott's comment, issue #310

### CODE REVIEW

**Comment by bgschiller** [comment]
Travis automatic deployment: https://331-pr-floorspace-js-NREL.surge.sh

**Comment by bgschiller** [comment]
Travis automatic deployment: https://331-pr-floorspace-js-NREL.surge.sh

**Comment by macumber** [comment]
@bgschiller is this safe to merge?

**Comment by bgschiller** [comment]
@macumber yep! I'll go ahead and do it.

**Pull request merged**
